default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: easy_pallet_challenge_api_development

test:
  <<: *default
  database: easy_pallet_challenge_api_test

production:
  <<: *default
  database: easy_pallet_challenge_api_production
  username: easy_pallet_challenge_api
  password: <%= ENV['EASY_PALLET_CHALLENGE_API_DATABASE_PASSWORD'] %>
